#8 Parse vcf and add to db
Bioinformatics-internship-EPAM/variant-annotator pull request #14
Opened 2021-03-28 13:52 UTC by Lapter57

Close #8 .

2021-03-28 22:27 UTC, RomanEgel requested changes

2021-03-28 22:27 UTC, RomanEgel commented on src/main/java/ru/spbstu/service/VariantService.java
> +public class VariantService {
i'd suggest to always create interfaces for services.
maybe we should make methods transactional?

2021-03-28 22:27 UTC, RomanEgel commented on src/main/java/ru/spbstu/model/Variant.java
> +    public static Variant from(final VcfRecord vcfRecord,
I think method signature doesn't fully reflect what this method does. I'd suggest to make it more understandable and differentiable from the below one.

2021-03-28 22:27 UTC, RomanEgel commented on src/main/java/ru/spbstu/service/VariantService.java
> +        final var variantToSave = variantRepository.findVariant(
if there is not such variant then varianToSave = variant and this means that you'll duplicate annotations.
If it is really upsert action then you should create new variant i guess.

2021-03-28 22:27 UTC, RomanEgel commented on src/main/java/ru/spbstu/controller/VcfController.java
> +            return ResponseEntity.badRequest().build();
is this really badRequest? Anyway i think it is better to provide some explaining message

2021-03-29 08:49 UTC, Kirvolque commented on src/main/java/ru/spbstu/controller/VcfController.java
> +    private final Reader<VcfRecord> vcfReader;
It would be better to move `vcfReader` injection to the service layer.

2021-03-29 08:49 UTC, Kirvolque commented on src/main/java/ru/spbstu/service/VariantService.java
> +                .forEach(this::upsert);
Please consider saving all records at once or maybe by chunks.

2021-04-06 07:22 UTC, RomanEgel commented on src/main/java/ru/spbstu/service/VariantService.java
> +    void saveWithBatch(InputStream inputStream, String dbName, int batchSize) throws IOException;
Does the service client should really specify batchSize? If we're presenting a batch option, I think batch size should be provided via configuration or, not really cool though, via constant. What do you think?

2021-04-14 15:47 UTC, Kirvolque requested changes

2021-04-14 15:47 UTC, Kirvolque commented on src/main/java/ru/spbstu/service/impl/VariantServiceImpl.java
> +    public Iterable<Variant> save(final InputStream inputStream,
Should we make these methods transactional?

2021-04-15 09:51 UTC, Kirvolque approved these changes

2021-04-15 20:11 UTC, JamieBirch approved these changes

2021-04-21 16:16 UTC, RomanEgel approved these changes
im ok

2021-04-24 18:01 UTC, merged