#10 connect swagger
Bioinformatics-internship-EPAM/variant-annotator pull request #16
Opened 2021-04-06 08:33 UTC by RomanEgel

2021-04-06 09:30 UTC, Kirill-Volkov-EPAM approved these changes

2021-04-07 15:54 UTC, JamieBirch commented
please add README and swagger url

2021-04-07 15:56 UTC, JamieBirch requested changes
please add README including:
swagger url
sonar project link
travis project link

2021-04-08 19:29 UTC, Kirvolque approved these changes

2021-04-20 04:44 UTC, RomanEgel commented
added readme

2021-04-25 10:22 UTC, JamieBirch approved these changes

2021-05-05 16:14 UTC, merged